### ISSUE TITLE
Panic setting up default network

### ISSUE THREAD

**Issue by Mierdin** [intel/multus-cni#122]
I was using multus before v3.0 and had the cni configuration working so that I could place pods on a default network for eth0, and if I omitted a network annotation on a pod, it would use this default network. Even if I added an annotation, it would use this default network for eth0, and the multus interfaces would start with the networks in the annotation.

However, since moving to v3.0, I am unable to get a Pod started without an annotation. The pod won't successfully start until I do. If I provide an annotation, it will not only spin up the pod, but it will have two network interfaces (`eth0` and the first multus-provided interface). This works but is a bit clunky because for simple applications that don't require multiple interfaces, I have to tack on a "dummy" network just to get it working.

Digging in a bit, the pod shows this message:

```
Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "bb204e95f7cc3a3e031accad8653b852dd316f294310966aa7a7cd9e6dabb737" network for pod "bb": NetworkPlugin cni failed to set up pod "bb_default" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input, failed to clean up sandbox container "bb204e95f7cc3a3e031accad8653b852dd316f294310966aa7a7cd9e6dabb737" network for pod "bb": NetworkPlugin cni failed to teardown pod "bb_default" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input]
```

The kubelet logs are a bit more telling, looks like a panic:

```
Aug 07 01:30:10 worker-lrq7 kubelet[19775]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 07 01:30:10 worker-lrq7 kubelet[19775]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xf22548]
Aug 07 01:30:10 worker-lrq7 kubelet[19775]: goroutine 1 [running]:
Aug 07 01:30:10 worker-lrq7 kubelet[19775]: main.cmdAdd(0xc42028b960, 0x0, 0x0, 0x0, 0x0, 0xc420096140, 0x5, 0x5, 0x0)
Aug 07 01:30:10 worker-lrq7 kubelet[19775]: /usr/src/multus-cni/gopath/src/github.com/intel/multus-cni/multus/multus.go:249 +0x698
Aug 07 01:30:10 worker-lrq7 kubelet[19775]: main.main.func1(0xc42028b960, 0x113abbc, 0x5)
Aug 07 01:30:10 worker-lrq7 kubelet[19775]: /usr/src/multus-cni/gopath/src/github.com/intel/multus-cni/multus/multus.go:334 +0x53
Aug 07 01:30:10 worker-lrq7 kubelet[19775]: github.com/intel/multus-cni/vendor/github.com/containernetworking/cni/pkg/skel.(*dispatcher).checkVersionAndCall(0xc4202b3340, 0xc42028b960, 0x1a70940, 0xc42008e510, 0x11b3d38, 0x0, 0xc4200ade58)
Aug 07 01:30:10 worker-lrq7 kubelet[19775]: /usr/src/multus-cni/gopath/src/github.com/intel/multus-cni/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:175 +0x19f
Aug 07 01:30:10 worker-lrq7 kubelet[19775]: github.com/intel/multus-cni/vendor/github.com/containernetworking/cni/pkg/skel.(*dispatcher).pluginMain(0xc4202b3340, 0x11b3d38, 0x11b3d40, 0x11b3d48, 0x1a70940, 0xc42008e510, 0x115fc02, 0x2f, 0x0)
Aug 07 01:30:10 worker-lrq7 kubelet[19775]: /usr/src/multus-cni/gopath/src/github.com/intel/multus-cni/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:210 +0x2f9
Aug 07 01:30:10 worker-lrq7 kubelet[19775]: github.com/intel/multus-cni/vendor/github.com/containernetworking/cni/pkg/skel.PluginMainWithError(0x11b3d38, 0x11b3d40, 0x11b3d48, 0x1a70940, 0xc42008e510, 0x115fc02, 0x2f, 0xc)
Aug 07 01:30:10 worker-lrq7 kubelet[19775]: /usr/src/multus-cni/gopath/src/github.com/intel/multus-cni/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:275 +0x118
Aug 07 01:30:10 worker-lrq7 kubelet[19775]: github.com/intel/multus-cni/vendor/github.com/containernetworking/cni/pkg/skel.PluginMain(0x11b3d38, 0x11b3d40, 0x11b3d48, 0x1a70940, 0xc42008e510, 0x115fc02, 0x2f)
Aug 07 01:30:10 worker-lrq7 kubelet[19775]: /usr/src/multus-cni/gopath/src/github.com/intel/multus-cni/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:290 +0x7a
Aug 07 01:30:10 worker-lrq7 kubelet[19775]: main.main()
Aug 07 01:30:10 worker-lrq7 kubelet[19775]: /usr/src/multus-cni/gopath/src/github.com/intel/multus-cni/multus/multus.go:332 +0x72
Aug 07 01:30:10 worker-lrq7 kubelet[19775]: E0807 01:30:10.285911   19775 cni.go:260] Error adding network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
Aug 07 01:30:10 worker-lrq7 kubelet[19775]: E0807 01:30:10.285945   19775 cni.go:228] Error while adding to cni network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
```

What's the current, v3.0-blessed way to provide a default network configuration? Below is my CNI configuration, it's pretty much unchanged from when it was working last, the only difference is the new kubeconfig created by the new deployment model in v3.0, and I'm pretty sure that's working since I can get things working with annotations - the default config below is what's not working.

```
[mierdin@worker-lrq7 ~]$ cat /etc/cni/net.d/1-multus-cni.conf
{
    "name": "node-cni-network",
    "type": "multus",
    "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig",
    "delegates": [{
        "type": "weave-net",
        "hairpinMode": true,
        "masterplugin": true
    }]
}
```

**Comment by Mierdin** [comment]
I had a chance to look at the commit history since v3.0, and I noticed this fix: https://github.com/intel/multus-cni/commit/d71fe3447fff150e7341456b3c38b5fb5eec7d3c
I'm guessing `kc` was `nil` and that's what was causing the issue. I'll test and validate the current `master` doesn't contain this issue, and if I can get it working, I'll close this issue and use the next release when it comes out.

**Comment by Mierdin** [comment]
Using the latest version of syringe does indeed fix the issue. Looking forward to v3.1! :smile:

Thanks for an awesome project!

**Comment by rkamudhan** [comment]
@Mierdin Will update the v3.0 tag commit..
