### ISSUE TITLE
Multus binary not found with custom kubernetes build

### ISSUE THREAD

**Issue by dougbtv** [intel/multus-cni#551]
Contributor reported that they're using the kubernetes script `./hack/local-up-cluster.sh`

Kubelet fails to run with:

```
I0831 09:35:53.557403    1590 client.go:94] Start docker client with request timeout=2m0s
W0831 09:35:53.564839    1590 docker_service.go:564] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
I0831 09:35:53.564873    1590 docker_service.go:241] Hairpin mode set to "hairpin-veth"
F0831 09:35:53.576722    1590 server.go:265] failed to run Kubelet: didn't find compatible CNI plugin with given settings &{HairpinMode:hairpin-veth NonMasqueradeCIDR:10.0.0.0/8 PluginName:multus PluginBinDirString:/opt/cni/bin PluginBinDirs:[/opt/cni/bin] PluginConfDir:/etc/cni/net.d PluginCacheDir:/var/lib/cni/cache MTU:0}: network plugin "multus" not found
goroutine 1 [running]:
```

Apparently the Multus CNI binary is installed:

```
$ ls /opt/cni/bin/
bandwidth  bridge  dhcp  firewall  flannel  host-device  host-local  ipvlan  loopback  macvlan  multus  portmap  ptp  sample  sbr  sriov  static  tuning  vlan

$ ls /etc/cni/net.d
00-multus.conf  10-flannel.conflist  87-podman-bridge.conflist  multus.d
```

And the conf looks OK:

```
$ sudo cat /etc/cni/net.d/00-multus.conf
{ "cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "logLevel": "debug", "logFile": "/tmp/multus.log", "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "name": "cbr0", "cniVersion": "0.3.1", "plugins": [ { "type": "flannel", "delegate": { "hairpinMode": true, "isDefaultGateway": true } }, { "type": "portmap", "capabilities": { "portMappings": true } } ] } ] }
```

**Comment by dougbtv** [comment]
Looks like this error comes from: https://github.com/kubernetes/kubernetes/blob/97145d685cad1e387346e152b8d48d836f808ce1/pkg/kubelet/dockershim/docker_service.go#L253

**Comment by dougbtv** [comment]
Build environment steps in https://gist.github.com/dougbtv/a6671c745f506036e523322f5c3ccd53

**Comment by dougbtv** [comment]
Turns out there was a mistake in the launch command:

```
<snipet> ..  NET_PLUGIN="multus" ./hack/local-up-cluster.sh -O
```

The NET_PLUGIN isn't supposed to be there.
